import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int t = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
         
		int boys = 0;
	    int girl = 0;
	    int kid2 = 0;
	    int kid3 = 0;
	    int kid4 = 0;
	    int sum = 0;
	    for(int i = 0; i<t; i++){
        while (boys == 0 || girl == 0){
		Random num = new Random(seed);
		if (num <= 0.5){
        boys ++;
		}
		else {
		girl ++; 
	    }
	    if (girl >=1 && boys >= 1){
	    sum = boys + girl;	
	    } 
	}
	   if (sum == 2){
       kid2++;
	   }	
	   if (sum == 3){
       kid3++;
	   }	
	   if (sum >= 4){
       kid4++;
	 }
	   boys = 0;
	   girl = 0;
   }
       double ageSum = kid2*2 + kid3*3 + kid4*4;
	   double avr = ageSum/t;

	   System.out.println("Average: " + avr + " children to get at least one of each gender." );
	   System.out.println("Number of families with 2 children: " + kid2 );
	   System.out.println("Number of families with 3 children: " + kid3 );
	   System.out.println("Number of families with 4 or more children: " + kid4 );	

	   if (kid2 > kid3 && kid2 > kid4) {
       System.out.println("The most common number of children is " + 2 + "." );

	   }else if (kid3 > kid2 && kid3 > kid4) {
	   System.out.println("The most common number of children is " + 3 + "." );

	}else 
	 System.out.println("The most common number of children is 4 or more.");
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
